FROM python:slim
RUN apt-get update && \ 
    apt install -y python3-pip && \
    python3 -m pip install splunk-opentelemetry requests && \
    apt -y autoremove && apt-get -y autoclean && \
    export PATH="$HOME/.local/bin:$PATH" && \
    splk-py-trace-bootstrap  && \
    mkdir /home/code
WORKDIR /home/code
COPY . /home/code/
