FROM python:slim
RUN apt-get update && \
    apt install -y python3-pip && \
    python3 -m pip install pip==21.0.1 && \
    apt install -y redis-server && \
    python3 -m pip install splunk-opentelemetry opentelemetry-instrumentation-redis redis && \
    apt-get install -y ntp && \
#   apt install -y procps && \
#   apt install -y net-tools && \
#   apt install -y curl && \
#   apt install -y netcat && \
#   apt install -y vim && \
    apt -y autoremove && apt-get -y autoclean && \
    export PATH="$HOME/.local/bin:$PATH" && \
    splk-py-trace-bootstrap  && \
    mkdir /home/code
ENV PYTHONUNBUFFERED true
WORKDIR /home/code
EXPOSE 6379
COPY . /home/code/
COPY redis.conf /etc/redis