clusterName: YOURCLUSTERHERE
splunkRealm: YOURREALMHERE
splunkAccessToken: YOURTOKENHERE

otelAgent:
  config:
    processors:
      metricstransform/prometheus_simple:
        transforms:
          - include: CustomGauge
            action: update
            new_name: TransformedGauge
    service:
      pipelines:
        metrics:
          processors:
            - memory_limiter
            - batch
            - resource
            - resourcedetection
            - metricstransform/prometheus_simple
