---
### Prometheus Endpoint Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
      - name: prometheus
        image: docker.io/stevelsplunk/splk-python
        ports:
          - name: http
            containerPort: 9090
        command: ["/bin/sh"]
        args: ["run-prometheus.sh"]
---
### Flask Server Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    name: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090