FROM python:slim
RUN mkdir /home/code
WORKDIR /home/code
COPY . /home/code/
COPY redis.conf /etc/redis
RUN apt-get update && \
    apt install -y redis-server && \
    apt install -y ntp && \
    export PATH="$HOME/.local/bin:$PATH" && \
    apt install -y python3-pip && \
    python3 -m pip install -r requirements.txt && \
    splk-py-trace-bootstrap && \
    apt -y autoremove && apt-get -y autoclean
EXPOSE 6379

#   apt install -y procps && \
#   apt install -y net-tools && \
#   apt install -y curl && \
#   apt install -y netcat && \
#   apt install -y vim && \
#   apt install -y iputils-ping && \