FROM python:slim
RUN apt-get update && \
    apt install -y redis-server && \
    apt install -y ntp && \
    apt install -y python3-pip && \
    python3 -m pip install pip==21.0.1 && \
    python3 -m pip install splunk-opentelemetry && \
    python3 -m pip install opentelemetry-api && \
    python3 -m pip install opentelemetry-instrumentation-redis && \
    python3 -m pip install redis && \
    apt -y autoremove && apt-get -y autoclean && \
    export PATH="$HOME/.local/bin:$PATH" && \
    splk-py-trace-bootstrap && \
    mkdir /home/code
WORKDIR /home/code
EXPOSE 6379
COPY . /home/code/
COPY redis.conf /etc/redis

#   apt install -y procps && \
#   apt install -y net-tools && \
#   apt install -y curl && \
#   apt install -y netcat && \
#   apt install -y vim && \
#   apt install -y iputils-ping && \