FROM python:slim
RUN apt-get update && \ 
    apt install -y python3-pip && \
    python3 -m pip install signalfx_tracing flask && \
    apt -y autoremove && apt-get -y autoclean && \
    export PATH="$HOME/.local/bin:$PATH" && \
    sfx-py-trace-bootstrap  && \
    mkdir /home/code
WORKDIR /home/code
EXPOSE 5000
COPY . /home/code/
