FROM ubuntu
RUN apt-get update && \
    apt install -y redis-server && \
    apt -y autoremove && apt-get -y autoclean && \
    mkdir /home/code
WORKDIR /home/code
EXPOSE 6379
COPY . /home/code/
COPY redis.conf /etc/redis