clusterName: YOURCLUSTERHERE
splunkRealm: YOUREREALMHERE
splunkAccessToken: YOURTOKENHERE

otelAgent:
  config:
    receivers:
      smartagent/prometheus-exporter:
        type: prometheus-exporter
        metricPath: "/"
        port: 8000
        host: localhost
    service:
      pipelines:
        metrics:
          receivers:
            - hostmetrics
            - kubeletstats
            - receiver_creator
            - smartagent/redis
            - smartagent/prometheus-exporter