clusterName: YOURCLUSTERHERE
splunkRealm: YOUREREALMHERE
splunkAccessToken: YOURTOKENHERE

# commented areas show how to add multiple prometheus endpoints

otelAgent:
  config:
    receivers:
      prometheus_simple:
        endpoint: "prometheus:9090"
#     prometheus_simple2:
#       endpoint: "prometheus2:9090"
    service:
      pipelines:
        metrics:
          receivers:
            - hostmetrics
            - kubeletstats
            - receiver_creator
            - signalfx
            - prometheus_simple
 #          - prometheus_simple2
