clusterName: YOURCLUSTERHERE
splunkRealm: YOUREREALMHERE
splunkAccessToken: YOURTOKENHERE

otelAgent:
  config:
    receivers:
      smartagent/prometheus-exporter:
        type: prometheus-exporter
        port: 8000
        host: prometheus-endpoint
    service:
      pipelines:
        metrics:
          receivers:
            - hostmetrics
            - kubeletstats
            - receiver_creator
            - signalfx
            - smartagent/prometheus-exporter